name: 'Docker Build Push'
description: 'Builds and pushes a Docker image to GitHub Container Registry'
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  context:
    description: 'The build context'
    required: true
  file:
    description: 'The Dockerfile to use'
    required: true
  platforms:
    description: 'The target platforms for the build'
    required: true
  sha_tag:
    description: 'The SHA tag for the image'
    required: true
  build_tags:
    description: 'The reference tag for the image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Build And Push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.build_tags }}

    - name: Image Digest
      shell: bash
      run: |
        echo "Image digest (amd64): ${{ steps.build-and-push.outputs.digest-amd64 }}"
        echo "Image digest (arm64): ${{ steps.build-and-push.outputs.digest-arm64 }}"

