name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Build Push
        uses: ./.github/actions/docker-build-push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          file: cli.Dockerfile
          platforms: linux/amd64,linux/arm64
          build_tags: |
            ghcr.io/rivet-gg/opengb:${{ github.sha }}
            ghcr.io/rivet-gg/opengb:${{ github.ref_name || '' }}

